apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base


images:
- name: gcr.io/dev-gke-301312/env-service
  newName: gcr.io/dev-gke-301312/env-service
  newTag: 079c0bbb3846c3c89c3c0c8f598986efc9f3453a